### ISSUE TITLE
不需要登录的评论在哪里

### ISSUE THREAD

**Issue by AmberSanyu** [hirCodd/vuepress-blog#1]
我只找到需要登录到评论，能不能给我这个菜鸡讲一讲不需要登录的评论是哪几个文件啊

**Comment by hirCodd** [comment]
就用我的这个就可以，里面有个comments.vue的文件，你可以看一下。

**Comment by AmberSanyu** [comment]
我下载了 但是运行不起来  yarn 总是有问题

**Comment by hirCodd** [comment]
我在readme提供了三种评论方案

**Comment by hirCodd** [comment]
截个图看一下

**Comment by AmberSanyu** [comment]
我删了 我要截图得重新下  请稍等一下

**Comment by AmberSanyu** [comment]
....奇了怪了 又运行起来了  我下了好几次   弄了半天了  就这次好了  麻烦你啦  我再看看  谢谢哈

**Comment by AmberSanyu** [comment]
但是评论那块没有，项目起来了，评论那块的404了

**Comment by hirCodd** [comment]
因为你没填appkey...在comments.vue里有那个东西

**Comment by AmberSanyu** [comment]
啊  project 那里出来了 但是评论不上Code -1: Request has been terminated
P

**Comment by hirCodd** [comment]
你需要去valine.js的网站上去看看。

**Comment by AmberSanyu** [comment]
好的把 谢啦
