### ISSUE TITLE
在iphone和ipad上使用Safari浏览器出现bug

### ISSUE THREAD

**Issue by Jokky6** [hirCodd/vuepress-blog#2]
在iphone和ipad上使用Safari浏览器浏览时，Nav上的点击失效，搜索事件也失效

**Comment by hirCodd** [comment]
您好，我这里在iPhone上都是正常的，你可以试试清除缓存试试。

**Comment by hirCodd** [comment]
由于本站没有使用cdn，所以加载速度略慢，vuepress使用vue.js，所以首页加载速度就有点慢！
